CREATE TABLE IF NOT EXISTS lnc_covers (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	isbn TEXT NOT NULL UNIQUE,
	cover_url TEXT NULL,
	error_message TEXT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);
